### ISSUE TITLE
[ISSUE] Custom OIDC not working with 8.4

### ISSUE THREAD

**Issue by czmirek** [camunda/camunda-platform-helm#1254]
**Describe the issue:**

I cannot make custom OIDC enabled in 8.4 work with minimal configuration.

**Actual behavior:**

Zeebe timeouts and logs an exception.

**Expected behavior:**

Zeebe verifies the token and returns the response for authenticated request.

**How to reproduce:**

- Setup a custom OIDC provider locally. I've setup custom KeyCloak but it shouldn't matter as long as it supports OIDC.
- Run this minimal helm chart 

```yaml
global:
  identity:
    auth:
      issuer: http://docker.projectport.internal:8083/realms/master
      # this is used for container to container communication
      issuerBackendUrl: http://docker.projectport.internal:8083/realms/master
      tokenUrl: http://docker.projectport.internal:8083/realms/master/protocol/openid-connect/token
      jwksUrl: http://docker.projectport.internal:8083/realms/master/protocol/openid-connect/certs
      type: "GENERIC"
      zeebe:
        clientId: zeebeclient
        audience: testaudience
        existingSecret: TZPLsKLEj0BlPB5NYyzGpYACPYhFh3P6

identity:
  enabled: false

optimize:
  enabled: false

connectors:
  enabled: false

tasklist:
  enabled: false

operate:
  enabled: false

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 5Gi

zeebe-gateway:
  replicas: 1

elasticsearch:
  master:
    replicaCount: 1
    # Request smaller persistent volumes.
    persistence:
      size: 5Gi
```

- Request authentication token for your OIDC authority
- Send a request with given Bearer token to Zeebe Gateway, e.g. ask for Topology endpoint

**Logs:**

Zeebe Gateway log

```
Jan 24, 2024 12:05:19 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall@4b1f4742
java.lang.IllegalStateException: io.camunda.identity.sdk.impl.rest.exception.RestException: request failed
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:617)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: io.camunda.identity.sdk.impl.rest.exception.RestException: request failed
        at io.camunda.identity.sdk.impl.rest.RestClient.send(RestClient.java:129)
        at io.camunda.identity.sdk.impl.rest.RestClient.request(RestClient.java:105)
        at io.camunda.identity.sdk.impl.generic.GenericAuthentication.wellKnownConfiguration(GenericAuthentication.java:169)
        at io.camunda.identity.sdk.impl.generic.GenericAuthentication.jwkProvider(GenericAuthentication.java:155)
        at io.camunda.identity.sdk.authentication.AbstractAuthentication.verify(AbstractAuthentication.java:172)
        at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:145)
        at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:122)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at io.camunda.identity.sdk.annotation.AnnotationProcessor.lambda$apply$0(AnnotationProcessor.java:33)
        at jdk.proxy2/jdk.proxy2.$Proxy120.verifyToken(Unknown Source)
        at io.camunda.zeebe.gateway.interceptors.impl.IdentityInterceptor.interceptCall(IdentityInterceptor.java:79)
        at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:269)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:701)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:408)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:613)
        ... 9 more
Caused by: java.net.ConnectException
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
        at io.camunda.identity.sdk.impl.rest.RestClient.send(RestClient.java:118)
        ... 24 more
Caused by: java.net.ConnectException
        at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Unknown Source)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(Unknown Source)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.channels.ClosedChannelException
        at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.beginConnect(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        ... 10 more
```

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: kind + HELM locally on Windows 11
- Chart version: 9.0.2
- Values file: see in issue

**Comment by aabouzaid** [comment]
@czmirek could you please test it again with the [9.3.0 release](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-9.3.0)?

**Comment by aabouzaid** [comment]
@czmirek According to the [docs](https://docs.camunda.io/docs/8.4/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider/?optionsType=helm), the components need that OIDC config like:

```
global:
  identity:
    auth:
      [...]
      zeebe:
        clientId: <Client ID from Step 2>
        audience: <Audience from Step 2>
        existingSecret: <Client secret from Step 2>
```

**Comment by aabouzaid** [comment]
I'm closing this since no updates so far. Feel free to open it again if needed.
