### ISSUE TITLE
[ISSUE] Zeebe broker cant delete snapshots

### ISSUE THREAD

**Issue by gasandjalilov** [camunda/camunda-platform-helm#1394]
**Describe the issue:**

Zeebe broker cant delete snapshots. Keeps every.

**Actual behavior:**

Send warning message.

and folders still exists.
drwxr-xr-x. 2 1000 nobody   28 Mar  3 22:10 609780-2197-610179-609891
drwxr-xr-x. 2 1000 nobody   28 Mar  3 22:15 615827-2197-615938-615962
-rw-r--r--. 1 1000 nobody  553 Mar  3 22:20 627523-2197-627802-627634.checksum
drwxr-xr-x. 2 1000 nobody 4096 Mar  3 22:20 627523-2197-627802-627634
drwxr-xr-x. 2 1000 nobody   28 Mar  3 22:20 621749-2197-621947-621860

with only file inside

[root@prod-k8s-master-02 609780-2197-610179-609891]# ls -ltr
total 1
-rw-r--r--. 1 1000 nobody 101 Mar  3 22:05 zeebe.metadata

**Expected behavior:**

Should delete folder with meta file in it.

**How to reproduce:**

used based values from repository and clean install.

**Logs:**

2024-03-03 17:19:39.984 [Broker-2] [zb-actors-1] [SnapshotStore-1] WARN 
      io.camunda.zeebe.snapshots.impl.FileBasedSnapshot - Failed to delete snapshot /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/46461728-2125-46626593-46626509
java.nio.file.DirectoryNotEmptyException: /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/46461728-2125-46626593-46626509
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.deleteIfExists(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.postVisitDirectory(FileUtil.java:213) ~[zeebe-util-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.postVisitDirectory(FileUtil.java:187) ~[zeebe-util-8.4.1.jar:8.4.1]
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists(FileUtil.java:114) ~[zeebe-util-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshot.delete(FileBasedSnapshot.java:154) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.lambda$deleteOlderSnapshots$18(FileBasedSnapshotStore.java:606) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.deleteOlderSnapshots(FileBasedSnapshotStore.java:603) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.persistNewSnapshot(FileBasedSnapshotStore.java:586) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.persistInternal(FileBasedTransientSnapshot.java:152) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$persist$3(FileBasedTransientSnapshot.java:113) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:75) ~[zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:88) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.4.1.jar:8.4.1]
2024-03-03 17:20:19.234 [Broker-2] [zb-actors-0] [SnapshotStore-2] INFO 
      io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 52024118-2324-52190401-52190060
2024-03-03 17:20:19.279 [Broker-2] [zb-actors-0] [SnapshotStore-2] WARN 
      io.camunda.zeebe.snapshots.impl.FileBasedSnapshot - Failed to delete snapshot /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/52018446-2324-52184474-52184388
java.nio.file.DirectoryNotEmptyException: /usr/local/zeebe/data/raft-partition/partitions/2/snapshots/52018446-2324-52184474-52184388
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.deleteIfExists(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.postVisitDirectory(FileUtil.java:213) ~[zeebe-util-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.util.FileUtil$FolderDeleter.postVisitDirectory(FileUtil.java:187) ~[zeebe-util-8.4.1.jar:8.4.1]
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at io.camunda.zeebe.util.FileUtil.deleteFolderIfExists(FileUtil.java:114) ~[zeebe-util-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshot.delete(FileBasedSnapshot.java:154) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.lambda$deleteOlderSnapshots$18(FileBasedSnapshotStore.java:606) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.deleteOlderSnapshots(FileBasedSnapshotStore.java:603) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore.persistNewSnapshot(FileBasedSnapshotStore.java:586) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.persistInternal(FileBasedTransientSnapshot.java:152) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$persist$3(FileBasedTransientSnapshot.java:113) ~[zeebe-snapshots-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:75) ~[zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:88) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.4.1.jar:8.4.1]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.4.1.jar:8.4.1]

**Environment:**

- Platform: Selfhosted
- Helm CLI version: 3.10.0
- Chart version: 8.4.1
- Values file: [Values](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml)

**Comment by aabouzaid** [comment]
@gasandjalilov The link in the value points to the values file in the main branch.
To help, more info about the platform (e.g. Kubernetes version), and the actual values file used in the deployment in addition to Zeebe logs.

**Comment by aabouzaid** [comment]
@gasandjalilov The link in the value points to the values file in the main branch.
To help, more info about the platform (e.g. Kubernetes version), and the actual values file used in the deployment.

**Comment by gasandjalilov** [comment]
@aabouzaid correct, I am using exact that values file from main branch.

**Comment by jessesimpson36** [comment]
@gasandjalilov ,  I'm confused, I see that you're using the values.yaml from the main branch, which should not be used except for development.

I also see 
> Chart version: 8.4.1

And yet we do not have a  helm chart version named 8.4.1. To get the chart version, you can run:
```
helm list -n <NAMESPACE>
```

I'm also not sure why the file permissions on your system are set with the `nobody` group, when it should have been changed to the configured `fsGroup`.  Could you clarify what kind of kubernetes installation you have?

**Comment by gasandjalilov** [comment]
Issue is solved in Camunda 8.4.6
