### ISSUE TITLE
[ISSUE] Custom OIDC not working

### ISSUE THREAD

**Issue by StAngerGordun** [camunda/camunda-platform-helm#1806]
**Describe the issue:**

I cannot make custom OIDC with minimal configuration

**Actual behavior:**

`URI with undefined scheme` error

**Expected behavior:**

Zeebe verifies the token and returns the response for authenticated request.

**How to reproduce:**

- use a custom OIDC provider. I use okta
- Run this minimal helm chart
```yaml
global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: true
      issuer: "https://trial-9725476.okta.com/oauth2/default"
      issuerBackendUrl: "https://trial-9725476.okta.com/oauth2/default"
      tokenUrl: "https://trial-9725476.okta.com/oauth2/default/v1/token"
      jwksUrl: "https://trial-9725476.okta.com/oauth2/default/v1/keys"
      type: "GENERIC"
      zeebe:
        clientId: "<my client id>"
        existingSecret:  "<my secret>"
        tokenScope: "<some scope>"
        audience: "api://default"


# Disable identity as part of the Camunda core
identity:
  enabled: false
identityKeycloak:
  enabled: false

optimize:
  enabled: false

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
  debug: true
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "6Gi"

zeebeGateway:
  replicas: 1

connectors:
  enabled: true
  inbound:
    mode: disabled

elasticsearch:
  master:
    replicaCount: 1
    # Request smaller persistent volumes.
    persistence:
      size: 15Gi

```

**Logs:**

Zeebe Gateway log

```
May 15, 2024 8:26:17 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall@6de70a11
java.lang.IllegalStateException: java.lang.IllegalArgumentException: URI with undefined scheme
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:617)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: URI with undefined scheme
	at java.net.http/jdk.internal.net.http.common.Utils.newIAE(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.checkURI(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(Unknown Source)
	at io.camunda.identity.sdk.impl.rest.RestClient.request(RestClient.java:60)
	at io.camunda.identity.sdk.impl.generic.GenericAuthentication.getPermissions(GenericAuthentication.java:139)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:215)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:164)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.camunda.identity.sdk.annotation.AnnotationProcessor.lambda$apply$0(AnnotationProcessor.java:33)
	at jdk.proxy2/jdk.proxy2.$Proxy108.verifyToken(Unknown Source)
	at io.camunda.zeebe.gateway.interceptors.impl.IdentityInterceptor.interceptCall(IdentityInterceptor.java:79)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:269)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:701)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:408)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:613)
	... 9 more

May 15, 2024 8:26:17 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall@1cf9eb57
java.lang.IllegalStateException: java.lang.IllegalArgumentException: URI with undefined scheme
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:617)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: URI with undefined scheme
	at java.net.http/jdk.internal.net.http.common.Utils.newIAE(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.checkURI(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(Unknown Source)
	at io.camunda.identity.sdk.impl.rest.RestClient.request(RestClient.java:60)
	at io.camunda.identity.sdk.impl.generic.GenericAuthentication.getPermissions(GenericAuthentication.java:139)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:215)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:164)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.camunda.identity.sdk.annotation.AnnotationProcessor.lambda$apply$0(AnnotationProcessor.java:33)
	at jdk.proxy2/jdk.proxy2.$Proxy108.verifyToken(Unknown Source)
	at io.camunda.zeebe.gateway.interceptors.impl.IdentityInterceptor.interceptCall(IdentityInterceptor.java:79)
	at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:269)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:701)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:408)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:613)
	... 9 more
```

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: kind + HELM locally on macOs 12.0.1
- Helm CLI version: v3.13.3
- Chart version: 10.0.5
- Values file:  see in issue

**Comment by aabouzaid** [comment]
@camunda/identity I need your help with this please :raised_hands:

**Comment by Ben-Sheppard** [comment]
Hey @aabouzaid and @StAngerGordun - the error appears to be originating from:
```
	at io.camunda.identity.sdk.impl.rest.RestClient.request(RestClient.java:60)
	at io.camunda.identity.sdk.impl.generic.GenericAuthentication.getPermissions(GenericAuthentication.java:139)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:215)
	at io.camunda.identity.sdk.authentication.AbstractAuthentication.verifyToken(AbstractAuthentication.java:164)
```

I can see that in the values file Identity is `enabled:false`, Identity is required in this setup so that Zeebe is able to retrieve the permissions mapped to the token.

Please could you enable/configure Identity and retry? As a hint, `identityKeycloak` can remain as false however `identityPostgres` will need to be enabled (to support Identity).

**Comment by aabouzaid** [comment]
@Ben-Sheppard Thanks for the suggestion :raised_hands: 
@StAngerGordun I will close this issue but feel free to open it again if needed.
