### ISSUE TITLE
Elasticsearch can't find master

### ISSUE THREAD

**Issue by Thessi** [camunda/camunda-platform-helm#321]
Helm: 3.9.0

I tried to install the chart with the commands provided in the Readme to my minikube
```
helm repo add camunda https://helm.camunda.io
helm repo update
helm install camunda-test camunda/camunda-platform
```
Nothing else was done or configured differently.

Now my Elasticsearch pods don't start up, because they can't find a master (despite them supposedly being master nodes):
```
{"type": "server", "timestamp": "2022-05-30T07:24:52,290Z", "level": "WARN", "component": "o.e.c.c.ClusterFormationFailureHelper", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and this node must discover master-eligible nodes [elasticsearch-master-0, elasticsearch-master-1] to bootstrap a cluster: have discovered [{elasticsearch-master-1}{DFj1duVWSGunhK9Q1G40fA}{GunDtYv2Q_qrMkoKsITOMg}{172.17.0.7}{172.17.0.7:9300}{cdfhilmrstw}]; discovery will continue using [] from hosts providers and [{elasticsearch-master-1}{DFj1duVWSGunhK9Q1G40fA}{GunDtYv2Q_qrMkoKsITOMg}{172.17.0.7}{172.17.0.7:9300}{cdfhilmrstw}] from last-known cluster state; node term 0, last-accepted version 0 in term 0" }
{"type": "server", "timestamp": "2022-05-30T07:34:23,995Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-1", "message": "path: /_cluster/health, params: {wait_for_status=green, timeout=1s}", 
"stacktrace": ["org.elasticsearch.discovery.MasterNotDiscoveredException: null",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:297) [elasticsearch-7.17.1.jar:7.17.1]",
"at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:345) [elasticsearch-7.17.1.jar:7.17.1]",
"at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:263) [elasticsearch-7.17.1.jar:7.17.1]",
"at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:660) [elasticsearch-7.17.1.jar:7.17.1]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.17.1.jar:7.17.1]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]",
"at java.lang.Thread.run(Thread.java:833) [?:?]"] }
```

Are any additional configurations necessary?

**Comment by Zelldon** [comment]
Hey @Thessi thanks for trying the helm charts. If you use minikube it is likely that you're running into some resource constraints. Please check whether all pods came up successfully, via `kubectl get pods` are they ready? You can do a `kubectl describe` to get  more insights. 

For local usage we created this KIND values file https://github.com/camunda/camunda-platform-helm/blob/main/kind/camunda-platform-core-kind-values.yaml this might work for you as well.

Greets
Chris

**Comment by Thessi** [comment]
Most of them are running, but specifically the zeebe brokers and one gateway aren't ready either, I figured that they were dependent on Elastic. I will try KIND and if nothing works run it on a live cluster with more resources. Thanks :)

**Comment by Zelldon** [comment]
I will close this for now. Please reopen if it doesn't work or you still stuck.
