### ISSUE TITLE
[ISSUE] Operate not working after zeebe update

### ISSUE THREAD

**Issue by michelefa1988** [camunda/camunda-platform-helm#573]
**Describe the issue:**
After upgrading from `camunda-cloud/ccsm-helm=0.0.23` to `camunda/camunda-platform=8.16` and elastic search from `7.16.2` to `7.17.1` zeebe operate throws the following errors

```
2023-02-28 12:28:46.470 ERROR 9 --- [ import_3] i.c.o.z.ImportJob : Import is not possible for Zeebe version: 1.3
```
In an attempt to resolve the above, we then deleted the Elastic search disks and restarted Elastic Search but now the following error is thrown.

```
 [type=index_not_found_exception, reason=no such index [operate-import-position-1.0.0_alias]]
```
Zeebe is pointing to the Elastic search helm chart provided by `elastic/elasticsearch`

I was expecting that restarting 1 zeebe pod should have recreated the indices and therefore operate would start operating normally. 

**Expected behavior:**

No Errors are displayed in the logs and operate works correctly 
**How to reproduce:**

This happened when updating production. All our dev/test/prod updates happen via code and I am 100% sure the configs are identical (except for specs/urls etc). We did not encounter such an issue on dev/test.

**Logs:**

```

2023-02-28 14:31:15.536  WARN 7 --- [ecords_reader_2] o.e.c.RestClient                         : request [POST http://elasticsearch-master:9200/operate-import-position-1.0.0_alias/_search?typed_keys=true&max_concurrent_shard_requests=5&search_type=query_then_fetch&batched_reduce_size=512] returned 1 warnings: [299 Elasticsearch-7.17.1-e5acb99f822233d62d6444ce45a4543dc1c8059a "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
2023-02-28 14:31:15.536 ERROR 7 --- [ecords_reader_2] i.c.o.z.RecordsReader                    : Elasticsearch exception [type=index_not_found_exception, reason=no such index [operate-import-position-1.0.0_alias]]

org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=index_not_found_exception, reason=no such index [operate-import-position-1.0.0_alias]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:178) ~[elasticsearch-7.17.6.jar!/:7.17.6]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2461) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2184) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
	at io.camunda.operate.zeebeimport.ImportPositionHolder.getLatestLoadedPosition(ImportPositionHolder.java:135) ~[operate-importer-8.1.6.jar!/:?]
	at io.camunda.operate.zeebeimport.ImportPositionHolder.getLatestScheduledPosition(ImportPositionHolder.java:116) ~[operate-importer-8.1.6.jar!/:?]
	at io.camunda.operate.zeebeimport.RecordsReader.readAndScheduleNextBatch(RecordsReader.java:144) ~[operate-importer-8.1.6.jar!/:?]
	at io.camunda.operate.zeebeimport.RecordsReader.readAndScheduleNextBatch(RecordsReader.java:136) ~[operate-importer-8.1.6.jar!/:?]
	at io.camunda.operate.zeebeimport.RecordsReader.run(RecordsReader.java:132) ~[operate-importer-8.1.6.jar!/:?]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.24.jar!/:5.3.24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch-master.:9200], URI [/operate-import-position-1.0.0_alias/_search?typed_keys=true&max_concurrent_shard_requests=5&search_type=query_then_fetch&batched_reduce_size=512], status line [HTTP/1.1 404 Not Found]
Warnings: [Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [operate-import-position-1.0.0_alias]","resource.type":"index_or_alias","resource.id":"operate-import-position-1.0.0_alias","index_uuid":"_na_","index":"operate-import-position-1.0.0_alias"}],"type":"index_not_found_exception","reason":"no such index [operate-import-position-1.0.0_alias]","resource.type":"index_or_alias","resource.id":"operate-import-position-1.0.0_alias","index_uuid":"_na_","index":"operate-import-position-1.0.0_alias"},"status":404}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347) ~[elasticsearch-rest-client-7.17.6.jar!/:7.17.6]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313) ~[elasticsearch-rest-client-7.17.6.jar!/:7.17.6]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288) ~[elasticsearch-rest-client-7.17.6.jar!/:7.17.6]
		at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
		at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.17.6.jar!/:7.17.6]
		at io.camunda.operate.zeebeimport.ImportPositionHolder.getLatestLoadedPosition(ImportPositionHolder.java:135) ~[operate-importer-8.1.6.jar!/:?]
		at io.camunda.operate.zeebeimport.ImportPositionHolder.getLatestScheduledPosition(ImportPositionHolder.java:116) ~[operate-importer-8.1.6.jar!/:?]
		at io.camunda.operate.zeebeimport.RecordsReader.readAndScheduleNextBatch(RecordsReader.java:144) ~[operate-importer-8.1.6.jar!/:?]
		at io.camunda.operate.zeebeimport.RecordsReader.readAndScheduleNextBatch(RecordsReader.java:136) ~[operate-importer-8.1.6.jar!/:?]
		at io.camunda.operate.zeebeimport.RecordsReader.run(RecordsReader.java:132) ~[operate-importer-8.1.6.jar!/:?]
		at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.24.jar!/:5.3.24]
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
		at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
		at java.lang.Thread.run(Unknown Source) ~[?:?]

```
**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: Azure
- Chart version: 8.1.6
- Values file: Can be provided later

**Comment by aabouzaid** [comment]
@michelefa1988 there is no direct support to migrate from the old charts to the new ones.
The deperacted chart `ccsm-helm` 0.0.23 has Zeebe/Operate v1.3.4, and the chart `camunda-platform` 8.1.16 use Zeebe/Operate 8.1.x.

Check the update guides for different versions as follows:
https://docs.camunda.io/docs/guides/update-guide/introduction/

But that's a manual process outside the Helm chart.

Also, please take a look at the current versioning convention for Helm charts:
https://github.com/camunda/camunda-platform-helm#versioning
