### ISSUE TITLE
[ISSUE] existingSecret.name does not appear to work when trying to use your own secret in values.yaml

### ISSUE THREAD

**Issue by jessesimpson36** [camunda/camunda-platform-helm#615]
**Describe the issue:**
Related to [SUPPORT-16602](https://jira.camunda.com/browse/SUPPORT-16602)

When the user specifies in their values.yaml file 
```
...
operate:
  existingSecret:
    name: "identity-secrets"
...
tasklist:
  existingSecret:
    name: "identity-secrets"
...
optimize:
  existingSecret:
    name: "identity-secrets"
...
```
The identity pod will fail with the following java stacktrace:

```

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:763) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at io.camunda.identity.Application.main(Application.java:18) ~[classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[identity.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[identity.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[identity.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[identity.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because the return value of "io.camunda.identity.impl.keycloak.config.record.KeycloakClient.secret()" is null
	at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.validateClientSecret(ClientInitializationService.java:183) ~[classes!/:?]
	at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.processClient(ClientInitializationService.java:63) ~[classes!/:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.process(ClientInitializationService.java:59) ~[classes!/:?]
	at io.camunda.identity.impl.keycloak.initializer.KeycloakClientInitializer.run(KeycloakClientInitializer.java:34) ~[classes!/:?]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760) ~[spring-boot-3.0.5.jar!/:3.0.5]
	... 13 more
```

There is a valid working way of specifying the secret name if you change your config to 
```
...
operate:
  existingSecret: "identity-secrets"
...
tasklist:
  existingSecret: "identity-secrets"
...
optimize:
  existingSecret: "identity-secrets"
...
```

I suspect that specifying the secret value in `name`  once worked because there were [PR's introduced](https://github.com/camunda/camunda-platform-helm/pull/311/files#diff-609aa2cf213c08fe9b6145258c304e28651062b7d1ee7bab5f560a9b079230abR398) specifically to test that the value in `existingSecret.name` may be used in the helm chart.  

**Actual behavior:**
The identity pod will crash with the following java stacktrace:

```

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:763) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at io.camunda.identity.Application.main(Application.java:18) ~[classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[identity.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[identity.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[identity.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[identity.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because the return value of "io.camunda.identity.impl.keycloak.config.record.KeycloakClient.secret()" is null
	at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.validateClientSecret(ClientInitializationService.java:183) ~[classes!/:?]
	at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.processClient(ClientInitializationService.java:63) ~[classes!/:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.process(ClientInitializationService.java:59) ~[classes!/:?]
	at io.camunda.identity.impl.keycloak.initializer.KeycloakClientInitializer.run(KeycloakClientInitializer.java:34) ~[classes!/:?]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760) ~[spring-boot-3.0.5.jar!/:3.0.5]
	... 13 more
```

**Expected behavior:**
All pods start up without errors.

**How to reproduce:**

To reproduce the failure case:

1. `git checkout camunda-platform-8.2.0`
2. git apply [0001-config-reproduced-on-camunda-platform-8.2.0.patch.txt](https://github.com/camunda/camunda-platform-helm/files/11255128/0001-config-reproduced-on-camunda-platform-8.2.0.patch.txt)
3. `make helm.install`

To reproduce a working config:

1. `git checkout camunda-platform-8.2.0`
2. git apply [0001-alternative-existingSecret-values.patch.txt](https://github.com/camunda/camunda-platform-helm/files/11255139/0001-alternative-existingSecret-values.patch.txt)
3. make helm.install

**Logs:**

[cpt-identity-logs.txt](https://github.com/camunda/camunda-platform-helm/files/11255148/cpt-identity-logs.txt)

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: Local Kind Cluster
- Helm CLI version: 
```
> helm version
version.BuildInfo{Version:"v3.11", GitCommit:"", GitTreeState:"", GoVersion:"go1.20.2"}
```
- Chart version: 8.2.0
- Values file: [values.yaml.txt](https://github.com/camunda/camunda-platform-helm/files/11255161/values.yaml.txt)

**Comment by jessesimpson36** [comment]
We should first decide if we want to support the 
```
existingSecrets:
  name: <value>
```
syntax. If not, we should remove the unit tests, docs, and relevant code that uses that format.

**Comment by jessesimpson36** [comment]
This might not be a valid issue.   On [SUPPORT-16602](https://jira.camunda.com/browse/SUPPORT-16602), Support team revealed to me a flaw in my test where specifying secrets with
```
operate:
    existingSecret: <value>
```
would result in secrets getting generated rather than the ones we created manually being used.

**Comment by jessesimpson36** [comment]
I'm going to close this issue, since I think my explanation of the problem was not valid, and this stacktrace is represented in another issue.

Related: https://github.com/camunda/camunda-platform-helm/issues/622
