### ISSUE TITLE
[ISSUE] Identity fails to start because of the Connectors var

### ISSUE THREAD

**Issue by aabouzaid** [camunda/camunda-platform-helm#622]
**Describe the issue:**

Identity fails to start because the Connectors secret has a typo, and it [uses Operate key](https://github.com/camunda/camunda-platform-helm/blob/9dcb9de857d01d6a98aaef47a7e4d6623e3655f5/charts/camunda-platform/charts/identity/templates/connectors-secret.yaml#L1). It fails when the Operate `existingSecret` is used so the secret is not generated and the Keycloak client seed of the Connectors.

Also, I've found another issue where it's not possible to use `existingSecret.name` to refer to the actual existing secret key for Connectors. Right now, it's only possible to use `existingSecret` to provide the text password (it's used in the upgrade).

**Actual behavior:**

**Expected behavior:**

The var `KEYCLOAK_CLIENTS_0_SECRET` should always be generated to make sure Identity doesn't fail (in the future, when we migrate to a flat chart structure, we can disable the `KEYCLOAK_CLIENTS_0_*` vars completely when Connectors is disabled).

**How to reproduce:**

Use existing secret for Operate:

```
global:
  identity: 
    auth:
      operate:
        existingSecret:
          name: custom-secrets
```

**Logs:**

When `KEYCLOAK_CLIENTS_0_SECRET` is empty, Identity fails with the following error:

```
2023-04-13 15:19:02.209 ERROR 1 --- [           main] o.s.b.SpringApplication                  : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:763) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.5.jar!/:3.0.5]
	at io.camunda.identity.Application.main(Application.java:18) ~[classes!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[identity.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[identity.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[identity.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[identity.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because the return value of "io.camunda.identity.impl.keycloak.config.record.KeycloakClient.secret()" is null
	at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.validateClientSecret(ClientInitializationService.java:183) ~[classes!/:?]
	at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.processClient(ClientInitializationService.java:63) ~[classes!/:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.process(ClientInitializationService.java:59) ~[classes!/:?]
	at io.camunda.identity.impl.keycloak.initializer.KeycloakClientInitializer.run(KeycloakClientInitializer.java:34) ~[classes!/:?]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:760) ~[spring-boot-3.0.5.jar!/:3.0.5]
	... 13 more
```

**Environment:**

- Platform: Any (tested on GKE).
- Helm CLI version: v3.9.3
- Chart version: 8.2.0
- Custom Values: added above.

**Related to:**
[SUPPORT-16602](https://jira.camunda.com/browse/SUPPORT-16602)

**Comment by aabouzaid** [comment]
[Camunda Platform Helm chart v8.2.1](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-8.2.1) has been released which contains the fix for this issue.
