### ISSUE TITLE
[ISSUE] Identity fails to start because the Connectors secret is required even if connectors is not enabled

### ISSUE THREAD

**Issue by daniel-ewing** [camunda/camunda-platform-helm#642]
**Describe the issue:**

Identity fails when Connectors is not enabled:
```
connectors:
  enabled: false
```
And `global.identity.auth.connectors.existingSecret.name` is not set:
```
  identity:
    auth:
      publicIssuerUrl: "https://keycloak.c8.dev.local/auth/realms/camunda-platform"
      operate:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://operate.c8.dev.local"
      tasklist:
        existingSecret:
          name: dev-identity-secrets
        redirectUrl: "https://tasklist.c8.dev.local"
      optimize:
        existingSecret:
          name: dev-identity-secrets
```
And the specified `dev-identity-secrets` does not contain a value for the `connectors-secret` secret:
```
kubectl create secret generic dev-identity-secrets \
                              --from-literal=operate-secret=SetThisToMakeUpgradeEasy \
                              --from-literal=tasklist-secret=SetThisToMakeUpgradeEasy \
                              --from-literal=optimize-secret=SetThisToMakeUpgradeEasy
```
**Actual behavior:**

Identity pod won't start, the pod log indicates:
```

java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:763) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:750) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[spring-boot-3.0.5.jar!/:3.0.5]
        at io.camunda.identity.Application.main(Application.java:18) ~[classes!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[identity.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[identity.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[identity.jar:?]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[identity.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.isBlank()" because the return value of "io.camunda.identity.impl.keycloak.config.record.KeycloakClient.secret()" is null
        at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.validateClientSecret(ClientInitializationService.java:183) ~[classes!/:?]
        at io.camunda.identity.impl.keycloak.initializer.service.ClientInitializationService.processClient(ClientInitializationService.java:63)
```

**Expected behavior:**

If I am not using connectors, I should not need to set a value for  `global.identity.auth.connectors.existingSecret.name` and I should not need to add a value for `connectors-secret` in my own identity-secrets.

**How to reproduce:**

Configure your own secrets and values.yaml as above and try to deploy.

**Logs:**

Relevant log error above.

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: minikube
- Helm CLI version: 3.11.3
- Chart version: 8.2.1
- Values file: relevant section given above.

**Related To**
[SUPPORT-16866](https://jira.camunda.com/browse/SUPPORT-16866)

**Comment by aabouzaid** [comment]
Hi @daniel-ewing
That issue was meant to be fixed in v8.2.1, but it looks like it slipped from me.

So I just released [v8.2.2](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-8.2.2), and it works as expected (I've tested it manually), and it would be great to double-check and test it too.
