### ISSUE TITLE
[ISSUE] Operate and Tasklist misses IDENTITY_BASEURL to work with active resource authorizations 

### ISSUE THREAD

**Issue by rbcb-bedag** [camunda/camunda-platform-helm#824]
**Describe the issue:**

For activating resource authorizations, we need to set some env variables according to the [documentation](https://docs.camunda.io/docs/next/self-managed/concepts/access-control/resource-authorizations/)

Here is an example:
```yaml
    identity:
      #Allow Resource authorizations
      env:
          #https://docs.camunda.io/docs/self-managed/identity/deployment/configuration-variables/#feature-flags
        - name: RESOURCE_PERMISSIONS_ENABLED
          value: "true"
          #https://docs.camunda.io/docs/self-managed/identity/deployment/configuration-variables/#database-configuration
        - name: IDENTITY_DATABASE_HOST      #The host of the database
          value: "postgres"
        - name: IDENTITY_DATABASE_PORT      #The port of the database
          value: "5432"
        - name: IDENTITY_DATABASE_NAME      #The name of the database to connect to
          value: "postgres"
        - name: IDENTITY_DATABASE_USERNAME  #The username of a user with access to the database
          value: "postgres"
        - name: IDENTITY_DATABASE_PASSWORD  #The password of a user with access to the database
          value: "postgres"

    operate:
      env:
          #https://docs.camunda.io/docs/next/self-managed/operate-deployment/operate-authentication/#resource-based-permissions
          #camunda.operate.identity.resourcePermissionsEnabled
        - name: CAMUNDA_OPERATE_IDENTITY_RESOURCEPERMISSIONSENABLED
          value: "true"

    tasklist:
      env:
          #https://docs.camunda.io/docs/next/self-managed/tasklist-deployment/tasklist-authentication/#resource-based-permissions
          #camunda.tasklist.identity.resourcePermissionsEnabled
        - name: CAMUNDA_TASKLIST_IDENTITY_RESOURCE_PERMISSIONS_ENABLED
          value: "true"
```

**Actual behavior:**

The operate component isn't reachable when setting ``CAMUNDA_OPERATE_IDENTITY_RESOURCEPERMISSIONSENABLED``.
It directly redirects to the /noPermission subpage (even when you have all permissions e.g. wildcard on user demo for processes).
Following error comes in the logs when trying to open the gui of the operate component (it doesnt' matter wheter combined or seperate ingress classes are used):

```java
2023-08-08 13:33:58.978 ERROR 8 --- [io-8080-exec-10] i.c.o.w.s.i.IdentityController           : Error in authentication callback: 
io.camunda.identity.sdk.exception.InvalidConfigurationException: 'forToken' can only be used if baseUrl is provided
        at io.camunda.identity.sdk.annotation.AnnotationProcessor.validateBaseUrl(AnnotationProcessor.java:62) ~[identity-sdk-8.3.0-alpha3.jar!/:?]
        at io.camunda.identity.sdk.annotation.AnnotationProcessor.lambda$apply$0(AnnotationProcessor.java:30) ~[identity-sdk-8.3.0-alpha3.jar!/:?]
        at jdk.proxy2.$Proxy136.forToken(Unknown Source) ~[?:?]
        at io.camunda.operate.webapp.security.identity.IdentityAuthentication.retrieveResourcePermissions(IdentityAuthentication.java:126) ~[classes!/:?]
        at io.camunda.operate.webapp.security.identity.IdentityAuthentication.authenticate(IdentityAuthentication.java:144) ~[classes!/:?]
        at io.camunda.operate.webapp.security.identity.IdentityService.getAuthenticationFor(IdentityService.java:86) ~[classes!/:?]
        at io.camunda.operate.webapp.security.identity.IdentityController.loggedInCallback(IdentityController.java:81) ~[classes!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.10.jar!/:6.0.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.10.jar!/:6.0.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.10.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar!/:?]
        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:128) ~[spring-security-oauth2-resource-server-6.1.1.jar!/:6.1.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323) ~[spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224) [spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) [spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) [spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) [spring-security-web-6.1.1.jar!/:6.1.1]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) [spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) [spring-web-6.0.10.jar!/:6.0.10]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.0.10.jar!/:6.0.10]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.0.10.jar!/:6.0.10]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) [spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.0.10.jar!/:6.0.10]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-6.0.10.jar!/:6.0.10]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) [spring-web-6.0.10.jar!/:6.0.10]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-10.1.10.jar!/:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-10.1.10.jar!/:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: baseUrl must not be empty
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
        at org.apache.commons.lang3.Validate.notBlank(Validate.java:439) ~[commons-lang3-3.12.0.jar!/:3.12.0]
        at io.camunda.identity.sdk.annotation.AnnotationProcessor.validateBaseUrl(AnnotationProcessor.java:59) ~[identity-sdk-8.3.0-alpha3.jar!/:?]
        ... 125 more
```

The important log is at the beginning : 
```java
io.camunda.identity.sdk.exception.InvalidConfigurationException: 'forToken' can only be used if baseUrl is provided
```

A ``baseUrl`` isn't set for the operate component to comunicate with the identity component and therefore operate cannot figure out if your user have the permissions or not.

**Expected behavior:**

When activating resource authorization all components should be able to communicate with the identity component to figure out the permissions of an user.

**How to reproduce:**

The [Docker Compose](https://github.com/camunda/camunda-platform/blob/main/docker-compose.yaml) variant does work locally with resource authorization enabled. When comparing the differences between the docker compose and the helm chart we see, that two env variables aren't set in the pods.

```yaml
#docker-compose.yaml
#operate
CAMUNDA_OPERATE_IDENTITY_BASEURL=http://identity:8084
#tasklist
CAMUNDA_TASKLIST_IDENTITY_BASEURL=http://identity:8084
```

We can reproduce the behvaior of the helm chart by removing these env variables from the docker-compose.yaml.

Clone the repo
```bash
git clone https://github.com/camunda/camunda-platform.git
```

Comment the env variables in the docker-compose.yaml
```yaml
#- CAMUNDA_OPERATE_IDENTITY_BASEURL=http://identity:8084
#- CAMUNDA_TASKLIST_IDENTITY_BASEURL=http://identity:8084
```

Start the containers with resource authorization enabled
```bash
RESOURCE_AUTHORIZATIONS_ENABLED=true docker-compose up
```

When up open operate component in browser and see the same error like via a deployment with the helm chart
```bash
http://localhost:8081/
#redirect to http://localhost:8081/noPermission
#Error Stacktrace from above is visible in the operate container
```

**Temporary Workaround:**
We can set the missing env variables ourself in a values.yaml file:

```yaml
    operate:
      env:
        - name: CAMUNDA_OPERATE_IDENTITY_RESOURCEPERMISSIONSENABLED
          value: "true"
        - name: CAMUNDA_OPERATE_IDENTITY_BASEURL
          # http://camunda-identity:80/identity
          value: "http://<RELEASE-NAME>-identity:80/<IDENTITY-CONTEXTPATH>"

    tasklist:
      env:
        - name: CAMUNDA_TASKLIST_IDENTITY_RESOURCE_PERMISSIONS_ENABLED
          value: "true"
        - name: CAMUNDA_TASKLIST_IDENTITY_BASEURL
          # http://camunda-identity:80/identity
          value: "http://<RELEASE-NAME>-identity:80/<IDENTITY-CONTEXTPATH>"
```

Here the complete snippet for activating resource authorization with the workaround by setting baseUrls manually:
```yaml
    identity:
      #Allow Resource authorizations
      env:
          #https://docs.camunda.io/docs/self-managed/identity/deployment/configuration-variables/#feature-flags
        - name: RESOURCE_PERMISSIONS_ENABLED
          value: "true"
          #https://docs.camunda.io/docs/self-managed/identity/deployment/configuration-variables/#database-configuration
        - name: IDENTITY_DATABASE_HOST      #The host of the database
          value: "postgres"
        - name: IDENTITY_DATABASE_PORT      #The port of the database
          value: "5432"
        - name: IDENTITY_DATABASE_NAME      #The name of the database to connect to
          value: "postgres"
        - name: IDENTITY_DATABASE_USERNAME  #The username of a user with access to the database
          value: "postgres"
        - name: IDENTITY_DATABASE_PASSWORD  #The password of a user with access to the database
          value: "postgres"

    operate:
      env:
          #https://docs.camunda.io/docs/next/self-managed/operate-deployment/operate-authentication/#resource-based-permissions
          #camunda.operate.identity.resourcePermissionsEnabled
        - name: CAMUNDA_OPERATE_IDENTITY_RESOURCEPERMISSIONSENABLED
          value: "true"
        - name: CAMUNDA_OPERATE_IDENTITY_BASEURL
          # http://camunda-identity:80/identity
          value: "http://<RELEASE-NAME>-identity:80/<IDENTITY-CONTEXTPATH>"

    tasklist:
      env:
          #https://docs.camunda.io/docs/next/self-managed/tasklist-deployment/tasklist-authentication/#resource-based-permissions
          #camunda.tasklist.identity.resourcePermissionsEnabled
        - name: CAMUNDA_TASKLIST_IDENTITY_RESOURCE_PERMISSIONS_ENABLED
          value: "true"
          # http://camunda-identity:80/identity
          value: "http://<RELEASE-NAME>-identity:80/<IDENTITY-CONTEXTPATH>"
```

**Possible fix:**
If possible set the two env variables for the BASEURL of the identity component inside the helm chart.
Or better alternative would be to expose a new variable like ``resourceAuthorization`` and when set to true the helm chart sets the env variables by himself. 
Also the contextpath of identity needs to be part of the env variable.

**Related issues:**
#639 Might be related to this issue

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Chart version: 8.2.8

**Comment by jessesimpson36** [comment]
I believe this is fixed in 8.3.1.  we did add CAMUNDA_OPERATE_IDENTITY_BASEURL  to operate and a similar variable for tasklist.
